 // *********************** PRODUCT  *********************** //

### 
GET http://localhost:4000/api/v1/product?page=1

//// ?keyword=product2&category=laptop



/// ?keyword=product1&price[gte]=800&price[lte]=1200



###
POST http://localhost:4000/api/v1/product/new
Content-Type: application/json

{
    "name":"Product10",
    "desc":"Test product",
    "price": 100,
    "category" : "Laptop",
    "images":{
        "public_id":"sample id",
        "url":"sample"
    }
}

### 
PUT http://localhost:4000/api/v1/product/629445f7b243cb567b937213
Content-Type: application/json

{
    "name":"Product1",
    "desc":"Test product updated",
    "price": 1200,
    "category" : "Laptop",
    "images":{
        "public_id":"sample id",
        "url":"sample"
    }
}


###
DELETE http://localhost:4000/api/v1/product/629421eab8b9bed13f09db4a

###
GET http://localhost:4000/api/v1/product/629421f0b8b9bed13f09db4